/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package QuickSort;

public class App {

    public static void main(String[] args) {

        int[] arr = { 5, 12, 8, 9, 1, 10 ,1};
        QuickSort.sort(arr);
        QuickSort.printArray(arr);
    }
}
