/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package k.array.tree;

public class App {

    public static void main(String[] args) {
        int n = 6;
        KarrayTreeNode kTree = new KarrayTreeNode(n, 1);
        kTree.children[0] = new KarrayTreeNode(n, 2);
        kTree.children[1] = new KarrayTreeNode(n, 3);
        kTree.children[2] = new KarrayTreeNode(n, 4);
        kTree.children[3] = new KarrayTreeNode(n, 30);
        kTree.children[0].children[0] = new KarrayTreeNode(n, 5);
        kTree.children[0].children[1] = new KarrayTreeNode(n, 6);
        kTree.children[0].children[2] = new KarrayTreeNode(n, 7);
        kTree.children[0].children[4] = new KarrayTreeNode(n, 15);
        kTree.children[0].children[3] = new KarrayTreeNode(n, 15);
        kTree.children[0].children[5] = new KarrayTreeNode(n, 15);

        int n2 = 3;
        KarrayTreeNode root = new KarrayTreeNode(n, 1);
        root.children[0] = new KarrayTreeNode(n, 2);
        root.children[1] = new KarrayTreeNode(n, 3);
        root.children[2] = new KarrayTreeNode(n, 4);
        root.children[0].children[0] = new KarrayTreeNode(n, 5);
        root.children[0].children[1] = new KarrayTreeNode(n, 6);
        root.children[0].children[2] = new KarrayTreeNode(n, 7);
//      KarrayTreeNode.inorder(root);
        System.out.println(KarrayTreeNode.FizzBuzz(kTree));
        System.out.println(KarrayTreeNode.FizzBuzz(root));
    }
}
